/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author HABEEB
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCreateTitle = new javax.swing.JLabel();
        jNameLabel = new javax.swing.JLabel();
        jIDLabel = new javax.swing.JLabel();
        jAgeLabel = new javax.swing.JLabel();
        jGenderLabel = new javax.swing.JLabel();
        jDateLabel = new javax.swing.JLabel();
        jLevelLabel = new javax.swing.JLabel();
        jTeamLabel = new javax.swing.JLabel();
        jPositionLabel = new javax.swing.JLabel();
        jPhoneLabel = new javax.swing.JLabel();
        jEmailLabel13 = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jIDField = new javax.swing.JTextField();
        jGenderField = new javax.swing.JTextField();
        jAgeField = new javax.swing.JTextField();
        jLevelField = new javax.swing.JTextField();
        jDateField = new javax.swing.JTextField();
        jTeamField = new javax.swing.JTextField();
        jPhoneField = new javax.swing.JTextField();
        jPositionField = new javax.swing.JTextField();
        jEmailField = new javax.swing.JTextField();
        jPhotoLabel = new javax.swing.JLabel();
        jUploadButton = new javax.swing.JButton();
        jSubmitButton = new javax.swing.JButton();

        jCreateTitle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCreateTitle.setText("Create Employee File");

        jNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNameLabel.setText("Name");

        jIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jIDLabel.setText("ID");

        jAgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAgeLabel.setText("Age");

        jGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGenderLabel.setText("Gender");

        jDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateLabel.setText("Start Date");

        jLevelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLevelLabel.setText("Level");

        jTeamLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTeamLabel.setText("Team Info");

        jPositionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPositionLabel.setText("Position Title");

        jPhoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPhoneLabel.setText("Cell Phone Number");

        jEmailLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmailLabel13.setText("Email Address");

        jNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameFieldActionPerformed(evt);
            }
        });

        jIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDFieldActionPerformed(evt);
            }
        });

        jGenderField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderFieldActionPerformed(evt);
            }
        });

        jAgeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgeFieldActionPerformed(evt);
            }
        });

        jLevelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLevelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLevelFieldActionPerformed(evt);
            }
        });

        jDateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateFieldActionPerformed(evt);
            }
        });

        jTeamField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTeamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeamFieldActionPerformed(evt);
            }
        });

        jPhoneField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneFieldActionPerformed(evt);
            }
        });

        jPositionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPositionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPositionFieldActionPerformed(evt);
            }
        });

        jEmailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailFieldActionPerformed(evt);
            }
        });

        jPhotoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPhotoLabel.setText("Photo");

        jUploadButton.setText("Upload");
        jUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUploadButtonActionPerformed(evt);
            }
        });

        jSubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSubmitButton.setText("SUBMIT");
        jSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCreateTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNameLabel)
                            .addComponent(jIDLabel)
                            .addComponent(jAgeLabel)
                            .addComponent(jGenderLabel)
                            .addComponent(jDateLabel)
                            .addComponent(jLevelLabel)
                            .addComponent(jTeamLabel)
                            .addComponent(jPositionLabel)
                            .addComponent(jPhotoLabel)
                            .addComponent(jEmailLabel13)
                            .addComponent(jPhoneLabel))
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPositionField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUploadButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jCreateTitle)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhotoLabel)
                    .addComponent(jUploadButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIDLabel)
                    .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAgeLabel)
                    .addComponent(jAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenderLabel)
                    .addComponent(jGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateLabel)
                    .addComponent(jDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLevelLabel)
                    .addComponent(jLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTeamLabel)
                    .addComponent(jTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPositionLabel)
                    .addComponent(jPositionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPhoneLabel)
                    .addComponent(jPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jEmailLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameFieldActionPerformed

    private void jIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDFieldActionPerformed

    private void jGenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenderFieldActionPerformed

    private void jAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgeFieldActionPerformed

    private void jLevelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLevelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLevelFieldActionPerformed

    private void jDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateFieldActionPerformed

    private void jTeamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeamFieldActionPerformed

    private void jPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneFieldActionPerformed

    private void jPositionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPositionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPositionFieldActionPerformed

    private void jEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailFieldActionPerformed

    private void jUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUploadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUploadButtonActionPerformed

    private void jSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAgeField;
    private javax.swing.JLabel jAgeLabel;
    private javax.swing.JLabel jCreateTitle;
    private javax.swing.JTextField jDateField;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JTextField jEmailField;
    private javax.swing.JLabel jEmailLabel13;
    private javax.swing.JTextField jGenderField;
    private javax.swing.JLabel jGenderLabel;
    private javax.swing.JTextField jIDField;
    private javax.swing.JLabel jIDLabel;
    private javax.swing.JTextField jLevelField;
    private javax.swing.JLabel jLevelLabel;
    private javax.swing.JTextField jNameField;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jPhoneField;
    private javax.swing.JLabel jPhoneLabel;
    private javax.swing.JLabel jPhotoLabel;
    private javax.swing.JTextField jPositionField;
    private javax.swing.JLabel jPositionLabel;
    private javax.swing.JButton jSubmitButton;
    private javax.swing.JTextField jTeamField;
    private javax.swing.JLabel jTeamLabel;
    private javax.swing.JButton jUploadButton;
    // End of variables declaration//GEN-END:variables
}
